[package]
name = "svo-cpu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.18.0"
minifb = "0.19.3"

[profile.dev]
opt-level = 2
lto = "fat"

[profile.release]
opt-level = 2
lto = "fat"
